/**
 * Unit tests for Token & Sign module (C3)
 *
 * Test IDs:
 *   SIGN-01: Normal generate + verify passes (no exception)
 *   SIGN-02: Tampered token → TokenInvalidError
 *   SIGN-03: Replay attack (second consume) → TokenAlreadyConsumedError
 *   SIGN-04: Expired token → TokenExpiredError
 *   SIGN-05: command field tampered → TokenInvalidError
 *   SIGN-06: Token generated by different key → TokenInvalidError
 *   SIGN-07: verify() uses crypto.timingSafeEqual()
 *
 * Extra: loadConsumed() persists across restart simulation
 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import crypto from 'node:crypto';
import Database from 'better-sqlite3';
import { TokenService, TokenExpiredError, TokenInvalidError, TokenAlreadyConsumedError } from '../src/token/index.js';

// ── helpers ──────────────────────────────────────────────────────────────────

function makeDb(): Database.Database {
  const db = new Database(':memory:');
  db.exec(`
    CREATE TABLE IF NOT EXISTS consumed_tokens (
      token        TEXT PRIMARY KEY,
      task_id      TEXT NOT NULL,
      consumed_at  INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_consumed_tokens_at ON consumed_tokens(consumed_at);
  `);
  return db;
}

function makeService(db: Database.Database, key?: Buffer): TokenService {
  const hmacKey = key ?? crypto.randomBytes(32);
  return new TokenService(hmacKey, db);
}

const TASK_ID = 'f47ac10b-58cc-4372-a567-0e02b2c3d479';
const COMMAND = 'ls -la /etc';
const FUTURE_MS = Date.now() + 10 * 60 * 1000; // 10 minutes from now

// ── SIGN-01: normal generate → verify passes ─────────────────────────────────

describe('SIGN-01: normal token lifecycle', () => {
  it('generate() produces a 64-char hex token and valid approval URL', () => {
    const db = makeDb();
    const svc = makeService(db);

    const { token, approvalUrl } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(token).toMatch(/^[0-9a-f]{64}$/);
    expect(approvalUrl).toContain('https://approval.willson0v0.com/approve');
    expect(approvalUrl).toContain(`task_id=${encodeURIComponent(TASK_ID)}`);
    expect(approvalUrl).toContain(`token=${token}`);
    const expiresSec = Math.floor(FUTURE_MS / 1000);
    expect(approvalUrl).toContain(`expires=${expiresSec}`);
  });

  it('verify() does not throw for a valid, unconsumed, unexpired token', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).not.toThrow();
  });
});

// ── SIGN-02: tampered token → TokenInvalidError ───────────────────────────────

describe('SIGN-02: tampered token', () => {
  it('flipping one hex char causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // Flip the first character
    const flipped = token[0]! >= 'a'
      ? '0' + token.slice(1)
      : 'a' + token.slice(1);
    const tampered = flipped === token ? 'b' + token.slice(1) : flipped;

    expect(() => svc.verify(TASK_ID, COMMAND, tampered, expiresSec)).toThrowError(TokenInvalidError);
  });
});

// ── SIGN-03: replay attack → TokenAlreadyConsumedError ───────────────────────

describe('SIGN-03: replay attack', () => {
  it('consuming same token twice throws TokenAlreadyConsumedError on second verify', async () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // First time: verify + consume → should succeed
    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).not.toThrow();
    await svc.consume(token, TASK_ID);

    // Second time: verify → should throw TokenAlreadyConsumedError
    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(
      TokenAlreadyConsumedError
    );
  });
});

// ── SIGN-04: expired token → TokenExpiredError ────────────────────────────────

describe('SIGN-04: expired token', () => {
  it('token with expiresSec in the past throws TokenExpiredError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const pastMs = Date.now() - 5000; // 5 seconds ago
    const expiresSec = Math.floor(pastMs / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, pastMs);

    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(TokenExpiredError);
  });
});

// ── SIGN-05: command field tampered → TokenInvalidError ───────────────────────

describe('SIGN-05: tampered command field', () => {
  it('modified command in verify() causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // Use original token but different command
    expect(() =>
      svc.verify(TASK_ID, 'rm -rf /', token, expiresSec)
    ).toThrowError(TokenInvalidError);
  });

  it('modified taskId in verify() causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() =>
      svc.verify('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', COMMAND, token, expiresSec)
    ).toThrowError(TokenInvalidError);
  });
});

// ── SIGN-06: different key → TokenInvalidError ────────────────────────────────

describe('SIGN-06: token from different HMAC key', () => {
  it('token generated with key1, verified with key2 throws TokenInvalidError', () => {
    const db = makeDb();
    const key1 = crypto.randomBytes(32);
    const key2 = crypto.randomBytes(32);
    const svc1 = new TokenService(key1, db);
    const svc2 = new TokenService(key2, db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc1.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(TokenInvalidError);
  });
});

// ── SIGN-07: verify() uses crypto.timingSafeEqual() ──────────────────────────

describe('SIGN-07: timingSafeEqual usage', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('verify() calls crypto.timingSafeEqual() for constant-time comparison', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // Spy on crypto.timingSafeEqual
    const spy = vi.spyOn(crypto, 'timingSafeEqual');

    svc.verify(TASK_ID, COMMAND, token, expiresSec);

    expect(spy).toHaveBeenCalledOnce();
  });

  it('verify() calls timingSafeEqual even for invalid tokens (no short-circuit)', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    const tampered = 'a' + token.slice(1);
    const spy = vi.spyOn(crypto, 'timingSafeEqual');

    try {
      svc.verify(TASK_ID, COMMAND, tampered, expiresSec);
    } catch {
      // expected to throw
    }

    expect(spy).toHaveBeenCalledOnce();
  });
});

// ── Extra: loadConsumed() survives Daemon restart simulation ──────────────────

describe('loadConsumed(): replay detection after restart', () => {
  it('loads consumed tokens from SQLite so replay is detected after restart', async () => {
    const db = makeDb();
    const svc1 = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc1.generate(TASK_ID, COMMAND, FUTURE_MS);

    svc1.verify(TASK_ID, COMMAND, token, expiresSec);
    await svc1.consume(token, TASK_ID);

    // Simulate restart: new TokenService with same DB but fresh memory
    const svc2 = new TokenService(svc1['hmacKey'], db);
    await svc2.loadConsumed();

    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(
      TokenAlreadyConsumedError
    );
  });
});
