/**
 * Unit tests for Token & Sign module
 *
 * Covers:
 *   SIGN-01: Normal generate + verify passes (no exception)
 *   SIGN-02: Tampered token → TokenInvalidError
 *   SIGN-03: Replay attack (second consume) → TokenAlreadyConsumedError
 *   SIGN-04: Expired token → TokenExpiredError
 *   Extra:   loadConsumed() persists across restart simulation
 */

import { describe, it, expect, beforeEach } from 'vitest';
import crypto from 'node:crypto';
import Database from 'better-sqlite3';
import { TokenService, TokenExpiredError, TokenInvalidError, TokenAlreadyConsumedError } from './index.js';

// ── helpers ──────────────────────────────────────────────────────────────────

function makeDb(): Database.Database {
  const db = new Database(':memory:');
  db.exec(`
    CREATE TABLE IF NOT EXISTS consumed_tokens (
      token        TEXT PRIMARY KEY,
      task_id      TEXT NOT NULL,
      consumed_at  INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_consumed_tokens_at ON consumed_tokens(consumed_at);
  `);
  return db;
}

function makeService(db: Database.Database, key?: Buffer): TokenService {
  const hmacKey = key ?? crypto.randomBytes(32);
  return new TokenService(hmacKey, db);
}

const TASK_ID = 'f47ac10b-58cc-4372-a567-0e02b2c3d479';
const COMMAND = 'ls -la /etc';
const FUTURE_MS = Date.now() + 10 * 60 * 1000; // 10 minutes from now

// ── SIGN-01: normal generate → verify passes ─────────────────────────────────

describe('SIGN-01: normal token lifecycle', () => {
  it('generate() produces a 64-char hex token and valid approval URL', () => {
    const db = makeDb();
    const svc = makeService(db);

    const { token, approvalUrl } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(token).toMatch(/^[0-9a-f]{64}$/);
    expect(approvalUrl).toContain('https://approval.willson0v0.com/approve');
    expect(approvalUrl).toContain(`task_id=${encodeURIComponent(TASK_ID)}`);
    expect(approvalUrl).toContain(`token=${token}`);
    const expiresSec = Math.floor(FUTURE_MS / 1000);
    expect(approvalUrl).toContain(`expires=${expiresSec}`);
  });

  it('verify() does not throw for a valid, unconsumed, unexpired token', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).not.toThrow();
  });
});

// ── SIGN-02: tampered token → TokenInvalidError ───────────────────────────────

describe('SIGN-02: tampered token', () => {
  it('flipping one hex char causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // Flip the first character: '0'-'9' → 'a', 'a'-'f' → '0'
    const flipped = token[0]! >= 'a'
      ? '0' + token.slice(1)
      : 'a' + token.slice(1);
    const tampered = flipped === token
      ? 'b' + token.slice(1)   // ensure it's actually different
      : flipped;

    expect(() => svc.verify(TASK_ID, COMMAND, tampered, expiresSec)).toThrowError(TokenInvalidError);
  });

  it('modified command causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() =>
      svc.verify(TASK_ID, 'rm -rf /', token, expiresSec)
    ).toThrowError(TokenInvalidError);
  });

  it('modified taskId causes TokenInvalidError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() =>
      svc.verify('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', COMMAND, token, expiresSec)
    ).toThrowError(TokenInvalidError);
  });

  it('token generated by different key causes TokenInvalidError', () => {
    const db = makeDb();
    const key1 = crypto.randomBytes(32);
    const key2 = crypto.randomBytes(32);
    const svc1 = new TokenService(key1, db);
    const svc2 = new TokenService(key2, db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc1.generate(TASK_ID, COMMAND, FUTURE_MS);

    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(TokenInvalidError);
  });
});

// ── SIGN-03: replay attack → TokenAlreadyConsumedError ───────────────────────

describe('SIGN-03: replay attack', () => {
  it('consuming same token twice throws TokenAlreadyConsumedError on second verify', async () => {
    const db = makeDb();
    const svc = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);

    // First time: verify + consume → should succeed
    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).not.toThrow();
    await svc.consume(token, TASK_ID);

    // Second time: verify → should throw TokenAlreadyConsumedError
    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(
      TokenAlreadyConsumedError
    );
  });
});

// ── SIGN-04: expired token → TokenExpiredError ────────────────────────────────

describe('SIGN-04: expired token', () => {
  it('token with expiresSec in the past throws TokenExpiredError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const pastMs = Date.now() - 5000; // 5 seconds ago
    const expiresSec = Math.floor(pastMs / 1000);
    const { token } = svc.generate(TASK_ID, COMMAND, pastMs);

    expect(() => svc.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(TokenExpiredError);
  });

  it('token expiring exactly at now (expiresSec === nowSec) throws TokenExpiredError', () => {
    const db = makeDb();
    const svc = makeService(db);

    const nowSec = Math.floor(Date.now() / 1000) - 1; // just expired
    const { token } = svc.generate(TASK_ID, COMMAND, nowSec * 1000);

    expect(() => svc.verify(TASK_ID, COMMAND, token, nowSec)).toThrowError(TokenExpiredError);
  });
});

// ── Extra: loadConsumed() survives Daemon restart simulation ──────────────────

describe('Extra: loadConsumed() after restart', () => {
  it('loads consumed tokens from SQLite so replay is detected after restart', async () => {
    const db = makeDb();
    const svc1 = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc1.generate(TASK_ID, COMMAND, FUTURE_MS);

    // Consume the token in "first daemon instance"
    svc1.verify(TASK_ID, COMMAND, token, expiresSec);
    await svc1.consume(token, TASK_ID);

    // Simulate restart: create new TokenService instance with the SAME db but fresh memory
    const svc2 = new TokenService(svc1['hmacKey'], db);
    // Before loadConsumed, the in-memory set is empty
    // (but verify would still pass if set is empty — that's the bug loadConsumed prevents)

    // Load consumed tokens from DB
    await svc2.loadConsumed();

    // Now replay should be detected
    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(
      TokenAlreadyConsumedError
    );
  });

  it('without loadConsumed(), restart would miss the replay (demonstrates why loadConsumed is needed)', async () => {
    const db = makeDb();
    const svc1 = makeService(db);

    const expiresSec = Math.floor(FUTURE_MS / 1000);
    const { token } = svc1.generate(TASK_ID, COMMAND, FUTURE_MS);

    await svc1.consume(token, TASK_ID);

    // New instance, no loadConsumed — in-memory set is empty
    const svc2 = new TokenService(svc1['hmacKey'], db);
    // Without loadConsumed, verify passes (vulnerability if we forget to call it)
    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).not.toThrow();

    // After loadConsumed, it correctly throws
    await svc2.loadConsumed();
    expect(() => svc2.verify(TASK_ID, COMMAND, token, expiresSec)).toThrowError(
      TokenAlreadyConsumedError
    );
  });
});

// ── consume() and loadConsumed() correctness ─────────────────────────────────

describe('consume() and loadConsumed()', () => {
  it('consume() writes to SQLite', async () => {
    const db = makeDb();
    const svc = makeService(db);

    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);
    await svc.consume(token, TASK_ID);

    const row = db
      .prepare('SELECT token, task_id FROM consumed_tokens WHERE token = ?')
      .get(token) as { token: string; task_id: string } | undefined;

    expect(row).toBeDefined();
    expect(row!.token).toBe(token);
    expect(row!.task_id).toBe(TASK_ID);
  });

  it('loadConsumed() populates in-memory set from DB', async () => {
    const db = makeDb();
    const svc = makeService(db);

    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);
    await svc.consume(token, TASK_ID);

    const svc2 = new TokenService(svc['hmacKey'], db);
    await svc2.loadConsumed();

    // Access private field via cast for white-box test
    const consumedSet = (svc2 as unknown as { consumed: Set<string> }).consumed;
    expect(consumedSet.has(token)).toBe(true);
  });

  it('duplicate consume() is idempotent (INSERT OR IGNORE)', async () => {
    const db = makeDb();
    const svc = makeService(db);

    const { token } = svc.generate(TASK_ID, COMMAND, FUTURE_MS);
    await svc.consume(token, TASK_ID);
    // Second consume should not throw
    await expect(svc.consume(token, TASK_ID)).resolves.not.toThrow();
  });
});
